runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DATABASE_URL: "postgresql://postgres:postgres@34.146.158.88:5432/postgres"
  NEXTAUTH_URL: "https://event-keijiban.com"
  NEXTAUTH_SECRET: "TClfxO35YkOLpAmRDgYqjVZLHx8GWYq0NDh0eZQHdCU="
  NODE_ENV: "production"
  PORT: "8080"
  EMAIL_USER: "akio5451@gmail.com"
  EMAIL_PASSWORD: "ydxe lkzv ibeg lpsr"
  EMAIL_FROM: "akio5451@gmail.com"
  EMAIL_TO: "akio5451@gmail.com"

beta_settings:
  cloud_sql_instances: even-dragon-456911-e6:asia-northeast1:bulletin-board-db

handlers:
  - url: /.*
    script: auto
    secure: always

readiness_check:
  path: "/api/health"
  check_interval_sec: 10
  timeout_sec: 8
  failure_threshold: 3
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 8
  failure_threshold: 3
  success_threshold: 2

entrypoint: sh startup.sh 