runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/bulletin_board?host=/cloudsql/even-dragon-456911-e6:asia-northeast1:bulletin-board-db"
  NEXTAUTH_URL: "https://even-dragon-456911-e6.an.r.appspot.com"
  NEXTAUTH_SECRET: "TClfxO35YkOLpAmRDgYqjVZLHx8GWYq0NDh0eZQHdCU="
  NODE_ENV: "production"
  PORT: "8080"
  EMAIL_USER: "akio5451@gmail.com"
  EMAIL_PASSWORD: "ydxe lkzv ibeg lpsr"
  EMAIL_FROM: "akio5451@gmail.com"
  EMAIL_TO: "akio5451@gmail.com"

beta_settings:
  cloud_sql_instances: even-dragon-456911-e6:asia-northeast1:bulletin-board-db

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: npm run start 